version: '3.8'

services:
  api:
    build: .
    container_name: mymetric-api
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account-key.json
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./credentials:/app/credentials:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mymetric-network

  nginx:
    image: nginx:alpine
    container_name: mymetric-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - mymetric-network

networks:
  mymetric-network:
    driver: bridge 